import{a as B,S as E,i as a}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const M="https://pixabay.com/api/",R="52937189-e7de87ebecf7d1a373ae68931";async function p(o,t=1,n=15){const i={key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};return(await B.get(M,{params:i})).data}const h=document.querySelector(".gallery"),f=document.querySelector(".loader"),$=new E(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const t=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:s,comments:q,downloads:P})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${s}</p>
          <p><b>Comments:</b> ${q}</p>
          <p><b>Downloads:</b> ${P}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function O(){h.innerHTML=""}function y(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}const b=document.querySelector(".form"),x=b.querySelector("input[name='search-text']"),g=document.querySelector(".load-more");let c="",d=1;const w=15;let u=0,l=0;b.addEventListener("submit",H);g.addEventListener("click",A);async function H(o){if(o.preventDefault(),c=x.value.trim(),!c){a.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}d=1,l=0,O(),v(),y();try{const t=await p(c,d,w);if(u=t.totalHits,l=t.hits.length,t.hits.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),l<u&&S()}catch(t){a.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.error(t)}finally{L()}}async function A(){d+=1,v(),y();try{const o=await p(c,d,w);m(o.hits),l+=o.hits.length;const{height:t}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l>=u?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):S()}catch(o){a.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.error(o)}finally{L()}}function S(){g.classList.remove("is-hidden")}function v(){g.classList.add("is-hidden")}
//# sourceMappingURL=index.js.map
