import{a as b,S as w,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="52937189-e7de87ebecf7d1a373ae68931",S="https://pixabay.com/api/",q=15;async function u(r,e){const o={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:q};try{return(await b.get(S,{params:o})).data}catch(a){throw console.error("Помилка при запиті зображень:",a),a}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let E=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const e=r.map(o=>`
      <a class="gallery-item" href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </a>`).join("");f.insertAdjacentHTML("beforeend",e),E.refresh()}function M(){f.innerHTML=""}function p(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}function P(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}const B=document.querySelector("#search-form"),$=document.querySelector(".load-more");let c="",i=1,L=0;B.addEventListener("submit",H);$.addEventListener("click",O);async function H(r){if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),!c){n.warning({message:"Please enter a search term!"});return}i=1,M(),g(),p();try{const e=await u(c,i);if(L=e.totalHits,e.hits.length===0){n.info({message:"No images found. Try another query!"}),d();return}y(e.hits),d(),e.totalHits>15&&P()}catch{n.error({message:"Error fetching images!"})}}async function O(){i+=1,p();try{const r=await u(c,i);y(r.hits),d(),A();const e=Math.ceil(L/15);i>=e&&(g(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Error loading more images!"})}}function A(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
