import{a as q,S as P,i as n}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const B="https://pixabay.com/api/",E="52937189-e7de87ebecf7d1a373ae68931";async function p(o){const t={key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await q.get(B,{params:t})).data}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),M=new P(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const t=o.map(({webformatURL:a,largeImageURL:c,tags:e,likes:r,views:i,comments:S,downloads:v})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img class="galery-image" src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${v}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",t),M.refresh()}function R(){g.innerHTML=""}function y(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}const b=document.querySelector(".form"),$=b.querySelector("input[name='search-text']"),f=document.querySelector(".load-more");let l="",s=1;const d=15;let u=0;b.addEventListener("submit",O);f.addEventListener("click",x);async function O(o){if(o.preventDefault(),l=$.value.trim(),!l){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}s=1,R(),w(),y();try{const t=await p(l,s,d);if(u=t.totalHits,t.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),u>d&&H()}catch(t){n.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.error(t)}finally{L()}}async function x(){s+=1,y();try{const o=await p(l,s,d);m(o.hits);const{height:t}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),s*d>=u&&(w(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){n.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight"}),console.error(o)}finally{L()}}function H(){f.classList.remove("is-hidden")}function w(){f.classList.add("is-hidden")}
//# sourceMappingURL=index.js.map
